### ISSUE TITLE
definir la historia de usuario

### ISSUE THREAD

**Issue by cande2323** [ISPC-TST-ELECTRONICA-MICROCONTROLADA/proyecto-1-grupo-01#53]
# Definir la historia de usuario para organizar el repositorio segun requisitos del docente

- [x] Uh#1Tk#1Int_x : Cargar nombre en el readme principal.
- [x] Uh#1Tk#2Int_x : Actualizar documentación ESP32
- [x] Uh#1Tk#3Int_x : Actualizar Bibliotecas / Recursos

**Comment by cande2323** [comment]
Proyectos

**Comment by gastonloco** [comment]
se creo la historia de usuario #69
